# config/config.yml
exchange:
  name: kraken
  trading_pairs:
    - BTC/USD
    - ETH/USD
  timeframe: 1h  # Data timeframe

paper_trading:
  initial_balance: 10000  # USD
  simulate_slippage: true
  slippage_percentage: 0.1

strategy:
  name: simple_moving_average
  parameters:
    short_window: 20
    long_window: 50
    rsi_period: 14

risk_management:
  max_position_size: 0.1  # 10% of account
  max_open_positions: 3
  stop_loss_percentage: 2.0
  take_profit_percentage: 4.0

